//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerDoor
    {
        public int WorkerDoorId { get; set; }
        public int WorkerId { get; set; }
        public int DoorId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Door Door { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
