//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerWorkshop
    {
        public int WorkerWorkshopId { get; set; }
        public int WorkerId { get; set; }
        public int WorkshopId { get; set; }
        public int WorkShift { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
